### PR TITLE
Upgrade to Node 18 and update all deps

### PR DESCRIPTION
**Pull request by FraBle**
Node 12 has been [deprecated for GitHub Actions](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). This PR upgrades to Node 18. Additionally, it does:

- upgrade all npm dependencies
- upgrade used external GitHub Actions
- build the GitHub Action release with Node 18
- clean up the readme based on `markdownlint` feedback

### CODE REVIEW

**Comment by daryl-miller** [comment]
Thanks for the dependency updates :).

**Comment by FraBle** [comment]
@daryl-miller oh, damn, I was too slow. It has to get downgraded to Node 16 since. `using: node18` is not yet supported.

**Comment by FraBle** [comment]
I can prep another PR later tonight. I was able to get it running nicely with Node 16 in a project.

**Comment by daryl-miller** [comment]
All good!

I'm reverting and testing node 16 now :).

**Comment by daryl-miller** [comment]
Looks like npm have introduced breaking changes to how npm config is used in npm 9 which is bundled with the node 16 github action.

I'm looking into alternative approaches for setting the codeartifact authentication that's compatible with the CLI version of this tool.

```npm config set will no longer accept deprecated or invalid config options```

https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

**Comment by FraBle** [comment]
@daryl-miller out of curiosity, what config options are considered invalid now?

**Pull request merged**
